### ISSUE TITLE
Can integrate with objective-c project?

### ISSUE THREAD

**Issue by nvnguyenit** [lkzhao/Hero#108]

**Comment by BilalReffas** [comment]
Yes of course see this message #53 from @lkzhao 


"You can use Hero in ObjC via swift objc interoperation.
You can import Hero like this in OC:

#import <Hero/Hero-Swift.h>

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Everything should work as expected. Let me know if it doesn't go well. For
plugin development, you have to do it in swift since you cannot subclass
swift class in objective c. I would recommend to let one or two of your
engineers learn swift and implement theses. It is easy to do and will take
less time than porting Hero to objectiveC."
