### ISSUE TITLE
Alternative fade animation

### ISSUE THREAD

**Issue by AlexandrGraschenkov** [lkzhao/Hero#122]
<img width="373" alt="2017-02-26 18 20 37" src="https://cloud.githubusercontent.com/assets/964601/23340496/a1dda9e2-fc50-11e6-9c88-3ddf92d3d70c.png">
I have transition with `heroId` set to image view. When interactive transition appear, I can hold it on 0.5 percent of complete. The result 2 image views in transition has alpha 0.5. This produce image with low transparency (0.75 alpha). Is that way to get non transparent image in result?

I try this code, but didn't work:
```avatar.heroModifiers = [.beginWith(modifiers: [.opacity(1.0)]), .opacity(1.0)]```

**Comment by lkzhao** [comment]
Set both of your views' isOpaque to true will do the trick.

**Comment by AlexandrGraschenkov** [comment]
Didn't work for me. Maybe later I will dive deeper in Hero, now release is coming..

**Comment by AlexandrGraschenkov** [comment]
The image already cropped and have alpha pixels, that why `isOpaque` is true. Do you have idea how to disable fade effect?
I found in preprocessors this code, and think about add plugin.
```
if !fv.isOpaque || fv.alpha < 1 || !tv.isOpaque || tv.alpha < 1 {
  // cross fade if from/toViews are not opaque
  fvState.opacity = 0
}
```
But `HeroTargetState` is closed from modifiers outside library.

**Comment by filbertteo** [comment]
I'm running into the same problem as well. I've ensured that both my source and target views have `isOpaque` set to `true` and have an alpha of 1 (I printed out the values to the console). But in my case, the result is worse, because my target view doesn't render for some reason until the transition is complete, causing the source image to fade to 0 alpha, and the target view suddenly appears when the transition completes.

Would it be possible to add a hero modifier to allow preventing crossfade (and show the source view at 1 alpha until the transition completes) instead of relying on the `isOpaque` and alpha values of the source / target views?

**Comment by filbertteo** [comment]
@AlexandrGraschenkov @lkzhao I just tried out the fix from master branch. Crossfade still occurs. But the funny thing is that when I inspect the values when the code breaks in [MatchPreprocessor.swift](https://github.com/lkzhao/Hero/blob/caffb5d6977bb1abe88007fa1574aa210e7c15c6/Sources/MatchPreprocessor.swift#L51), `forceNonFade` is `true`, but the fading still happens.

I can't share a sample project, but if it helps, my source view is a UIImageView, and the target view is a UIScrollView.

**Comment by lkzhao** [comment]
Try removing the beginwith modifier

**Comment by filbertteo** [comment]
@lkzhao I didn't use any modifier other than `forceNonFade`. It's @AlexandrGraschenkov who used the `beginWith` modifier.

**Comment by peckda** [comment]
In MatchPreprocessor, I added `tvState.opacity = nil` when `forceNonFade` is `true` to fix my crossfade issues:

```
// no cross fade in this case, fromView is always displayed during the transition.
fvState.opacity = nil
tvState.opacity = nil
```
