### ISSUE TITLE
Documentation needs clarity

### ISSUE THREAD

**Issue by TheSwiftyCoder** [lkzhao/Hero#138]
It would be helpful to provide documentation on implementation of basic transitions. For example tried to use a few such as zoom and scale and got an error "HeroModifier has no member zoom".

Also how to implement the latest transitions (push, cover etc) as this is only shown in animated gif, not implemented.

Thanks :)

**Comment by lkzhao** [comment]
`zoom`, `push`, `cover`, etc.. are not heroModifiers. They are default animation types. 

Have you checkout the wikis yet?
* [Hero Modifiers](https://github.com/lkzhao/Hero/wiki/Hero-Modifiers)
* [Default Animation](https://github.com/lkzhao/Hero/wiki/Default-Animations)

**Comment by jesse-cohen** [comment]
I did check out the links which is why I reported the issue. Example:
"Starting with 0.3.0. **Hero provides several default transitions**. These can also be customized & combined with your custom heroID & heroModifiers. Makes transitions even easier to implement."

This implies that Hero is adding these transitions. This coupled with the images below makes it confusing.

**Comment by brightfuture** [comment]
Indeed I also find it really hard to understand how to achieve any animation with Hero, right now I just randomly set the modifier and hope it works as expected, which most of time doesn't. I just don't know how to use the modifiers.

**Comment by Manny7311** [comment]
When I try using this, hero_replaceViewController(with: myVC) it will go to the next viewController, but I can't get back with any action, and the first view is brought up through AppDelegate as a navigation controller.
