### ISSUE TITLE
crash in Hero.shared.end(), when pan too quickly

### ISSUE THREAD

**Issue by PatrickSCLin** [lkzhao/Hero#203]
when I pan an imageView in my app too quickly, it causes app crash sometimes,

context: HeroContext! is null

fatal error: unexpectedly found nil while unwrapping an Optional value
2017-05-16 10:58:52.556929+0800 soocii[44033:7935298] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by PatrickSCLin** [comment]
it is easy to reproduce in Hero samples.

just pan to dismiss an imageView in ImageViewController in super big velocity

then app crashes

**Comment by andreamazz** [comment]
I can confirm that the issue is here:
https://github.com/lkzhao/Hero/blob/master/Sources/Hero.swift#L210

there are cases in which the `complete(finished:)` function is called twice, once with finished set to true, and then to false. On complete the context (and other variables that are declared as IUOs) is set to nil:
https://github.com/lkzhao/Hero/blob/master/Sources/HeroBaseController.swift#L356

I'd suggest to drop the Implicitly unwrapped optionals all together, and early exit `complete(finished:)` when `finished` is `false`.  
I'd love to hear what you think @lkzhao 
Let me know if you need any help with this.

**Comment by PatrickSCLin** [comment]
any news ?

**Comment by BilalReffas** [comment]
Running on the same issue

**Comment by lkzhao** [comment]
Can you guys try the release-1.0 branch? let me know if the problem still persists.

```ruby
pod "Hero", :git => 'https://github.com/lkzhao/Hero.git', :branch => "release-1.0"
```

**Comment by BilalReffas** [comment]
@lkzhao I will check it and let you know :)

**Comment by BilalReffas** [comment]
I have some problems to update the framework I'm using Carthage.. :/ 
`github "lkzhao/Hero" "release-1.0"
`

**Comment by andreamazz** [comment]
@lkzhao 
I'm still experiencing this issue, there's a call to `animate` when context is already nil, being an IUO it crashes.

**Comment by BilalReffas** [comment]
@andreamazz do you use Carthage?

**Comment by andreamazz** [comment]
Nope, CocoaPods

**Comment by BilalReffas** [comment]
Looks like ` Hero.shared.end()` is away right?

**Comment by andreamazz** [comment]
> Replace with this Hero.shared.animationEnded(true) right?

I use `Hero.shared.finish()`

**Comment by PatrickSCLin** [comment]
it still can reproduce in branch of release 1.0
<img width="1512" alt="screen shot 2017-05-30 at 6 53 08 pm" src="https://cloud.githubusercontent.com/assets/2464698/26580228/ce42b902-4569-11e7-98d9-61241bba487d.png">

**Comment by BilalReffas** [comment]
Thank you @andreamazz

**Comment by BilalReffas** [comment]
Same for me @PatrickSCLin @andreamazz 😕

**Comment by ahartwel** [comment]
If you check out this commit (https://github.com/swarmnyc/Hero/commit/a08a6e4f647e26cd5954e690c73da454e661108a) in my forked version of hero, wrapping end and cancel in DispatchQueue.main.async blocks solved the crash when dragging/tapping too quickly for me

**Comment by PatrickSCLin** [comment]
any updates ? Hero is awesome framework but I can't use in production product with this issue

**Comment by iMSXServer** [comment]
This seams to fix it...

func pan() {
        let translation = panGR.translation(in: nil)
        let progress = translation.y / 2 / collectionView!.bounds.height
        switch panGR.state {
        case .began:
            collectionView?.removeGestureRecognizer(panGR)       //      <-------

            SuperHero(aView: self, id: ImageViewControllerFor, backColor: UIColor.black, transition: HeroDefaultAnimationType.fade)//.zoomSlide(direction: .right))
            return
        case .changed:
            Hero.shared.update(progress: Double(progress))
            if let cell = collectionView?.visibleCells[0]  as? ScrollingImageCell {
                let currentPos = CGPoint(x: translation.x + view.center.x, y: translation.y + view.center.y)
                Hero.shared.apply(modifiers: [.position(currentPos)], to: cell.imageView)
            }
        default:
            if progress + panGR.velocity(in: nil).y / collectionView!.bounds.height > 0.3 {
                Hero.shared.end()
            } else {
                Hero.shared.cancel()
            }
        }
    }

BTW I can't resist:
func SuperHero(aView: UIViewController, id: String, backColor: UIColor, transition: HeroDefaultAnimationType) {
    let vc = aView.storyboard!.instantiateViewController(withIdentifier: id)
    Hero.shared.disableDefaultAnimationForNextTransition()
    Hero.shared.setContainerColorForNextTransition(backColor)
    Hero.shared.setDefaultAnimationForNextTransition(transition)
    aView.hero_replaceViewController(with: vc)
}

**Comment by flowOZ** [comment]
This seams to fix it...

    func pan() {
        let translation = panGR.translation(in: nil)
        let progress = translation.y / 2 / collectionView!.bounds.height
        switch panGR.state {
        case .began:
            collectionView?.removeGestureRecognizer(panGR)   //HOW TO FIX IT THE CRASH

            SuperHero(aView: self, id: ImageViewControllerFor, backColor: UIColor.black, transition: HeroDefaultAnimationType.fade)//.zoomSlide(direction: .right))
            return
        case .changed:
            Hero.shared.update(progress: Double(progress))
            if let cell = collectionView?.visibleCells[0]  as? ScrollingImageCell {
                let currentPos = CGPoint(x: translation.x + view.center.x, y: translation.y + view.center.y)
                Hero.shared.apply(modifiers: [.position(currentPos)], to: cell.imageView)
            }
        default:
            if progress + panGR.velocity(in: nil).y / collectionView!.bounds.height > 0.3 {
                Hero.shared.end()
            } else {
                Hero.shared.cancel()
            }
        }
    }

BTW I can't resist:

    func SuperHero(aView: UIViewController, id: String, backColor: UIColor, transition: HeroDefaultAnimationType) {
        let vc = aView.storyboard!.instantiateViewController(withIdentifier: id)
        Hero.shared.disableDefaultAnimationForNextTransition()
        Hero.shared.setContainerColorForNextTransition(backColor)
        Hero.shared.setDefaultAnimationForNextTransition(transition)
        aView.hero_replaceViewController(with: vc)
    }

**Comment by zipme** [comment]
It seems it crashes if you are doing the transition within a UINavigationController.

https://github.com/lkzhao/Hero/blob/master/Sources/Hero.swift#L178

Because `self.animate()` is dispatched later into the main queue, if you pan too quickly, the `complete(finished: Bool)` gets called earlier which nils the `toViewController` hence the crash.

Wrapping the `finish()` call in a `DispatchQueue.main.async` seems to workaround this issue:

```swift
  DispatchQueue.main.async {
      Hero.shared.finish()
  }
```

**Comment by ajpallares** [comment]
I also found the same bug in Hero. 
When you call `Hero.shared.end()`, then, in line 253 of `Hero.swift`, the `toViewController` is set to `nil`.
If the call `Hero.shared.end()` occurs very soon after `popViewController()` was called (which can be achieved by quickly panning and releasing right after), line 253 gets executed before the `start()` method of `Hero` executes line 178: 

    self.animate()

where, in line 187 calls 

    context.unhide(view: toView)

Taking into account that the `toView` property is computed by

    internal var toView: UIView { return toViewController!.view }

This call fails because `toViewController` is being unwrapped while it is `nil`.

I could find a temporary solution by slightly delaying the call to `Hero.shared.end()`.

    DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.01, execute: {
        Hero.shared.end()
    })

It looks like this way, `Hero` has enough time to finish the call of the `start()` method before `end()` is executed. However, this is not the desired solution.

**Comment by k-nar** [comment]
I found that this bug occurred more often when there were some background thread doing heavy works (dynamic blurring in my case) 
following @ajpallares comment I do 

func heroSafeFinish()
{
        if(Hero.shared.state != .animating)
        {
            //anim did no start, wait a moment before finish
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.01, execute: {
                self.heroSafeFinish()
            })
        }
        else
        {
            Hero.shared.finish();
        }
    }

**Comment by caesss** [comment]
I implemented the solution by @ajpallares and it worked like a charm. Thank you very much!!!
