### ISSUE TITLE
UICollectionViewCells drawing outside of bounds when transitioning.

### ISSUE THREAD

**Issue by GoldenJoe** [lkzhao/Hero#221]
If you make a collection view that does not take up the entire screen:

|...........................|
|...Header View...|
|...........................|
|++++++++++++|
|.Collection View.|
|++++++++++++|

Scroll through the list so that some cells go past the top of the collection view, then perform a translate or fade animation. The cells that should be outside the collection view's bounds will draw on top of the header view.

**Comment by johndpope** [comment]
try adding to self.clipsToBounds = true in the collectionview cell.

**Comment by lkzhao** [comment]
The reason is because once a view is matched, its snapshot pull from the collection view to the global container view. 

One way to fix this is to set your header view's heroModifier to `[.forceAnimate, .useGlobalCoordinateSpace]`. This way Hero will create a snapshot for your header view too and insert it in the global container view. You might also need to adjust the zPosition of your header view.

**Comment by lkzhao** [comment]
Cleaning out old issues. Feel free to reopen.
