### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by MaeseppTarvo** [lkzhao/Hero#245]
Hey, I just found a weird bug(at least I think it is library bug). The bug is that if you apply the fade animation to tabbarcontroller and if you press tabs back and forth, the whole screen goes black. Basically it just makes everything to disappear except tab bar.

Is there any hotfix I can do?

This is what I mean. I can’t show you the view debug since I am typing it from my phone. If necessary I can post it later.

![img_0206](https://user-images.githubusercontent.com/8416295/28753596-6fbe7e7e-753f-11e7-9c0d-cafbc80deed9.PNG)

**Comment by Kamajabu** [comment]
Have you found solution yet? I've been thinking about delaying showing tab bar to user, but this solution is not really one I'm looking for...

**Comment by lkzhao** [comment]
Is this still happening in the 1.0.0-alpha? Thought I fixed this some times ago.

**Comment by JoniVR** [comment]
Still happening for me, on the latest pod version, even when using `heroTabBarAnimationType = .none` (on iOS 11 beta 5, real device, iPhone 6s+). Happens when I switch tabs fast.

Have tried this on an iPhone 6s (simulator) running iOS 10.3.1 and was not able to reproduce it so far (might be because I can't "tap" as fast on a simulator), will test on an iOS 10.3.1 device soon.

console right after it happened (on iOS 11 beta 5)
<img width="705" alt="schermafbeelding 2017-08-14 om 11 25 56" src="https://user-images.githubusercontent.com/7591717/29266031-7d574444-80e3-11e7-9b6a-8d308d7d4ce2.png">

**Comment by LemonRuss** [comment]
Y, still have it. Seems like it somehow put viewController under TabBar. Like it have problems with coordinateSystem. Will try to reproduce and add screen later

**Comment by myrilwan** [comment]
Olfll.kkiooioklllo oo
