### ISSUE TITLE
The CG extension overloads are declared internal but then used publicly

### ISSUE THREAD

**Issue by jimsmithm3** [lkzhao/Hero#27]
What I ran into was pulling your ImageGallery example code into my project as a baseline for modification to my needs.

What I immediately ran into was in ImageViewController.swift on line 67

ImageGallery/ImageViewController.swift:67:38: Binary operator '+' cannot be applied to two 'CGPoint' operands.

This is declared internal in CG+Hero.swift on line 76.  Since I am pulling this in as a pod while the example code is just an internal library I get the error and it doesn't.  

I had to change the CG+Hero.swift to public to get that code to compile in my project.  Should all the overloads just be made public? I am just starting to use this maybe there is a reason not to do that.  I would rather use pods than copy it locally if possible.

Thanks and this library really looks like it's going to be very useful.

**Comment by lkzhao** [comment]
I don't really want to expose that extension since it is half baked. If I expose them, you will get a duplicate implementation error during compilation if you also happen to use any of the swift extension libraries like SwifterSwift or ExSwift. If you need the file you can copy it locally. Or I would recommend checking out [SwifterSwift](https://github.com/omaralbeik/SwifterSwift/blob/master/README.md)
