### ISSUE TITLE
Swift 4 issue (1.0.0-alpha.4) in HeroCoreAnimationViewContext

### ISSUE THREAD

**Issue by RamblinWreck77** [lkzhao/Hero#277]
https://imgur.com/a/vYcLR

looks like a quick-fix

**Comment by mosn** [comment]
Hero started off really great, promising to simply transition animations!  and they delivered to some expect. But I find myself going away from it mostly because of errors like this and other to-be-discovered bugs. Don't get me wrong I appreciate that they put out something for me and I am not denying  that fact. But if you have a commitment it is better to see it fulfilled and not just leave it mid air. 

I would love to hear what is the reason for the lack of responsibility and if the community and do anything about it.
