### ISSUE TITLE
Does Hero work with TableViews or CollectionViews?

### ISSUE THREAD

**Issue by Joanii** [lkzhao/Hero#36]
When I click on a cell on a TableView or CollectionView the animation is perfect, but when I press the back button the TableView goes under the NavigationBar.
Hero is Enabled to true btw.

![screen shot 2017-01-10 at 22 18 04](https://cloud.githubusercontent.com/assets/8223362/21825123/b4225c62-d782-11e6-80d7-3ea43c5fbbcd.png)

**Comment by lkzhao** [comment]
Shouldn't happen. Might be a bug. If you disable Hero, does the problem go away? Can you provide a demo project so that I can better help you?

**Comment by Joanii** [comment]
When I disable Hero the problem goes away... 
The navigation bar that you see is a custom navBar and a question that pops in my head now is if Hero supports custom navigation bars (this navBar is from [Material Design](http://www.cosmicmind.com/material) ) ?. 
Here is a short demo of the problem.

[Demo.zip](https://github.com/lkzhao/Hero/files/697721/Demo.zip)

**Comment by lkzhao** [comment]
Should be fixed with this: https://github.com/lkzhao/Hero/commit/715610ad5a0cffa392097f35d3d5e505f00241ea

Apparently, the [Material](https://github.com/CosmicMind/Material) project doesn't support insets according to the layout guide. That is different from the default UINavigationController. But I should't have set the frame of the destination view controller either.
