### ISSUE TITLE
UIImageView not animating to contentMode

### ISSUE THREAD

**Issue by delox** [lkzhao/Hero#363]
I was under the impression that after pull request number 16, image transitions would take into consideration the contentMode of UIImageViews, but for scaleAspectFit, it is animating beyond the size of the image, before abruptly downsizing to the desired size

**Comment by AlexanderTheOkay** [comment]
What was the solution for this? I'm having the same issue.

I have a UIImageView in a UICollectionViewCell, set to aspectFill.
I'd like to animate it to a detail page using the same image, with a UIImageView set to aspectFit.

Currently, the image in the cell scales up to the frame of the detail page's UIImageView, and fades. But the detail page's image is actually smaller since it's set to aspectFit instead aspectFill.

I've played around with some options to try and get this to work, but no luck so far.
