### ISSUE TITLE
May I create a new hero repository written by Objective-C?

### ISSUE THREAD

**Issue by LucaGalaxy** [lkzhao/Hero#53]
our team want to import Hero into our project, but we want an OC version that may easy to maintain by us. :)
so I want to make an OC version from this repo, the copyright will still your's, I'll work as a translator

**Comment by lkzhao** [comment]
I wouldn't recommend doing so. It will be a quite a lot of work. Was there a specific reason that you would like to implement this in OC?

**Comment by LucaGalaxy** [comment]
yap cause our team has a lot of Engineers who are not so familiar with swift, but we really wanna use Hero in our project, it's so cool.
Also the OC version will make more easy for us to maintain or develop some new plugins

**Comment by lkzhao** [comment]
You can use Hero in ObjC via swift objc interoperation.
You can import Hero like this in OC:

#import <Hero/Hero-Swift.h>

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Everything should work as expected. Let me know if it doesn't go well. For
plugin development, you have to do it in swift since you cannot subclass
swift class in objective c. I would recommend to let one or two of your
engineers learn swift and implement theses. It is easy to do and will take
less time than porting Hero to objectiveC.

**Comment by MagicNew** [comment]
> You can use Hero in ObjC via swift objc interoperation.
> You can import Hero like this in OC:
> 
> #import <Hero/Hero-Swift.h>

<Hero/Hero-Swift.h> file not found when I use “ pod 'Hero' ”. Any suggestion？
