### ISSUE TITLE
Somewhere hard to understand

### ISSUE THREAD

**Issue by PhilCai1993** [lkzhao/Hero#55]
I am confused about [this](https://github.com/lkzhao/Hero/blob/65349d0dc3a411c97cd86c53b9c2abaedd55ec9a/Sources/HeroDefaultAnimatorViewContext.swift#L211)  in `HeroDefaultAnimatorViewContext .swift`
```
// duration is 0.2 @ 0 to 0.375 @ 500
defaultDuration = 0.208 + Double(movePoints.clamp(0, 500)) / 3000
``` 

After checking [Duration and easing](https://material.io/guidelines/motion/duration-easing.html#duration-easing-dynamic-durations), I still cannot figure out what does the magic number `0.208`, `3000` mean.

Could you please give some tips? How is the default animation duration determined?

Thanks a lot.

**Comment by lkzhao** [comment]
movePoints is the distance the object moves. It is clamped to 0...500. When it is over 500 I just use 500 as the value. 500/3000 is 0.16666667. That plus 0.208 is around 0.375. So when the object moves 500+ points the duration is 0.375. When the object moves 0 points, the duration is 0.208.

**Comment by PhilCai1993** [comment]
Thanks for answering. But I still have two questions.
Why is `3000`?
And when the movement is 0, why there is still a non-zero duration?

**Comment by lkzhao** [comment]
When the movement is zero, it might be animating opacity, cornerRadius
etc.. therefore we still need a duration. Also for short movement, making
it too fast won't provide a good user experience.

It is 3000, because I want to map 0...500 to 0.208...0.375. With that, I
need a value of 3000 since 500/(0.375-0.208) ~= 3000. To be exact, I was
thinking about mapping 0...500 to 0.2...0.375. That would need a magic
divider of 2,857.14.

**Comment by PhilCai1993** [comment]
It helps, thanks again!
