### ISSUE TITLE
Interactive Transitions

### ISSUE THREAD

**Issue by dave4506** [lkzhao/Hero#67]
Hey, You noted that we can make interactive transitions. I have been scouring the example and the issues for some documentation or example, but I can't find any. 

Can @lkzhao give me a few pointers? Like I'm trying to find how you did the image viewer fade animation. 

Many Thanks

**Comment by lkzhao** [comment]
@dave4506 Interactive transition guide is coming next week. I didn't made any documentation because the interactive transition API has been undergoing major changes. For now, you can download the example project and checkout the imageViewer example and the new Apple HomePage example. Actually, it is pretty straight forward to build one.

**Comment by lkzhao** [comment]
@dave4506 Checkout http://lkzhao.com/2017/02/05/hero-interactive-transition.html. More coming soon.
