### ISSUE TITLE
Breaking changes between versions

### ISSUE THREAD

**Issue by adellibovi** [lkzhao/Hero#84]
Hi Luke,

Thanks for the amazing job you are doing for Hero.

Since yesterday I started to use Hero for one of my apps and I'm having problem with a transition, also it performs differently between versions.
What I would like to do is: scale a view to full screen and having some cards sliding from the bottom.

I tried several options:
One is having all the view available from the source view: so no modifiers involved.
With 0.1.8 it works fine and this is the result:
https://cl.ly/1z2i2r1K3Y1O
With 0.1.9 and 0.2.0 there is a little flash in one of the white cards:
https://cl.ly/0o1A3V3O0e3m
With 0.3.0 took from master this is what happens (same as before + hiding on the way back) and there is also an alpha transition of the source view on the way back:
https://cl.ly/3e2S3n1k0V15

Then I tried removing the white cards from the source view and using the translate modifier and the transition of the white cards disappear:
https://cl.ly/1B160n182p0H
If i use the zPosition I can see the transition only on the way back:
https://cl.ly/36401t1C0u0Q

Ideally I was hoping to use, the latest version with the modifier. not having to duplicate the view inside the source and without "the alpha animation" introduced in that version, but looks like the only way I could get it work it's with the 0.1.8 and having the duplicate views.

I really would like to help and to collaborate to the project, but I still don't have enough knowledge of Hero. If you could hint me on what I'm doing wrong or try something else, or if you think it's a bug where I should investigate more, maybe I can send a PR for that :)

Anyway thanks a lot, for taking the time for reading this.

**Comment by adellibovi** [comment]
I could make it work with the latest version (0.3.0) doing a series of changes:
The background view was a separated view, now it's the view of the destination controller, that solved the alpha transition noticed on the dismiss.
I removed the copied views from the source and replaced with the translate modifier. That gave an animation for both way (presenting and dismissing) but the line was not straight. So I tried to use the useGlobalCoordinateSpace, that fixed the straight line on presenting, but on the dismissing the white cards just disappear, to fixed that I had to add zPosition modifier when dismissing.

Maybe when using useGlobalCoordinateSpace, something wrong happens with the zPosition and I have to set on dismissing?

**Comment by lkzhao** [comment]
First of all. Thanks for such a detailed feedback! Glad that some one is testing this out. Hero is still in beta under heavy development, there are two more features I would like to add to the library before making a stable version 1.0. Currently, a good stable version to fallback to would be 0.1.7 if you so desire. But I would love to get your guys' feedbacks on newer versions, I will try to respond quickly to solve any bugs you guys are experiencing.

Let me explain the effects you are seeing and why they work/not work. I will just target 0.3.0 here.

1. The alpha fade when your background view isn't the root view. This effect is the default animation provided Hero. If your destination/source root view doesn't have animation specified, Hero will perform its default animation on source/destination root views. You can disable this behavior by calling 
```swift
Hero.shared.setDefaultAnimationForNextTransition(.none)
```
Or
```swift
Hero.shared.disableDefaultAnimationForNextTransition()
```
Or just specify some custom animations to either root views, like what you did here changing the background view to the root view.

2. You shouldn't need the copied views in your initial VC. Though they should work. The glitch you are seeing with the white views can be eliminated by setting the `isOpaque` property to `false` on your white views. Currently, Hero reads the `isOpaque` property to determine if it need to do a cross fade. If both source/destination view's `isOpaque` property is set to true, then it will just overlay the destination view on top of the source view during animation. Hero does this because it assumes the destination view can fully cover the source view. But in your case, it doesn't, the some white views are transparent and cannot cover the source views. In the next version, I will have Hero check the `alpha` properties, too.

3. The `zPosition` modifier shouldn't be needed in your case with `useGlobalCoordinateSpace`. might still be a bug. Would love to get my hands on your project if that is possible. Let me try see whats wrong.

**Comment by adellibovi** [comment]
Thanks for clarifying about the default animation 👍 

I was researching a bit more about the bug. It looks like the view hierarchy is wrong while animating with global coordinates.

Look here:

The selected view is the background, while the three views before are the white cards
<img width="253" alt="screen shot 2017-02-11 at 19 30 57" src="https://cloud.githubusercontent.com/assets/67916/22856423/661dc646-f091-11e6-807d-73230dcf728f.png">

Instead without the .global I get the white cards views inside the background view.
<img width="262" alt="screen shot 2017-02-11 at 19 32 56" src="https://cloud.githubusercontent.com/assets/67916/22856422/65fb0b7e-f091-11e6-8a34-2f9a875e5f33.png">

I'll try to recreate this case if you think it can help

**Comment by adellibovi** [comment]
Wait, I just saw your latest commit :) let me try that

**Comment by lkzhao** [comment]
Please check if the latest master fixes this problem. Help me create
another issue if it doesn't.

**Comment by adellibovi** [comment]
Just tried out, the bug persist. Do you want me to close this issue and create a new one?

**Comment by lkzhao** [comment]
Yea sure!

**Comment by adellibovi** [comment]
Ok thanks!
