### ISSUE TITLE
Hero.shared.end()

### ISSUE THREAD

**Issue by Rozariozaro** [lkzhao/Hero#90]
Sometimes Hero.shared.end() ends the transitions but does not update the views to the current progress so it gets stuck and no userinteraction is available to dismiss the viewcontroller.

I have also tried using Hero.shared.end(animate:true), It freezes the app.

**Comment by lkzhao** [comment]
Can you give me more context? Is it in a navigation controller? Does it happen when user flicks very fast? One thing that might be causing this is that you can called update(progress:) after you called end.

**Comment by Rozariozaro** [comment]
This is my handlePan method

`func handlePan(gestureRecognizer: UIPanGestureRecognizer) {
        Hero.shared.defaultAnimation = .fade
        
        let translation = panGR.translation(in: nil)
        let progress = -(translation.x / 2 / songImgVw.bounds.width)
        
        switch panGR.state {
        case .began:
            _ = navigationController?.popViewController(animated: true)
        case .changed:
            let imagePosition = CGPoint(x: translation.x + songImgVw.center.x, y: songImgVw.center.y)
            
            print(progress)
            Hero.shared.update(progress: Double(progress))
            Hero.shared.apply(modifiers: [.position(imagePosition)], to: songImgVw)
            
        default:
            if progress - panGR.velocity(in: nil).x / songImgVw.bounds.width > 0.3 {
                Hero.shared.update(progress: Double(progress))
                Hero.shared.end()
            } else {
                Hero.shared.cancel()
            }
            
        }
    }
`

It is in a navigationController. I am pushing to the current viewController with collectionView didSelect method.

I have included a modifier of [.beginWithIfMatched(modifiers: [.zPosition(3)]), .arc] for the image to transition from viewcontrollers..

It happens only for some instances the total app freezes.

**Comment by lkzhao** [comment]
Thanks, I know whats happening if it is in a UINavigationController. I have seen this before. One more question, are you on the latest version? I remember trying to fix it a few commits back. But I am not sure if that fix was successful since it is hard to reproduce.

**Comment by Rozariozaro** [comment]
Yeah I am on the latest source file downloaded from github.

**Comment by lkzhao** [comment]
cool, thanks! I will try to fix it in the next version.

**Comment by lkzhao** [comment]
@Rozariozaro Can you try again with the latest master?

**Comment by Rozariozaro** [comment]
Yeah now it is working fine.. Thank you for solving this issue so swiftly.. Thumbs up..

**Comment by leeprobert** [comment]
Can you give us some more information about the fix for this? I am seeing the same thing. I have an interactive transition between view controllers, and sometimes the app just seems to freeze. It is like the transition has not ended and given back control.

**Comment by HiroshiHorie** [comment]
I am having the same issue too.

**Comment by cnluocj** [comment]
emmmmm, I am having the same issue too.

**Comment by StainlessStlRat** [comment]
I am experiencing this issue but it is fully re-creatable for me. 

I have a collection view with images, when selected I unmark the previous heroID, and set the ID to the image that was clicked. I then push to a DetailViewController that inherits from tableView. 

I have a gesture recognizer attached to this view so that I can still swipe back. I had to set the delegate of that recognizer to work simultaneously with the tableView's scroll gesture recognizer or else it wouldn't scroll.

If I scroll that view and then hit the "back" button, it freezes. Every time.
If I scroll that view and slide left a little, starting the transition some, and let it slide back and THEN hit the back button, it works just fine.
If I go to the detail view controller and don't scroll, it never freezes.
